<?php

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Tree;

/**
 * @var string              $module
 * @var array<GedcomRecord> $types
 * @var array<>             $recordTypes
 * @var string              $title
 * @var string              $header_recs
 * @var string              $header_acts
 * @var array<>             $tagsLabels
 * @var string              $routeSDbAjax
 * @var array<>             $tagsXREFs
 * @var Tree                $tree
 */

?>

<?php foreach ($types as $key => $class) :      // test if there are records for this type ... ?>
    <?php if (array_key_exists($key, $recordTypes)) : ?>
        <?php $records = $recordTypes[$key]; ?>
        <?php $count = count($records); ?>
        <?php $Theader = 'TSM-' . $key; ?>
        <table class="table wt-facts-table TSM-facts-table" style="display:none">
            <colgroup>
                <col span="1" style="width: 30%;">
                <col span="1" style="width: 60%;">
                <col span="1" style="width: 10%;">
            </colgroup>
            <thead>
                <tr>
                    <th name="<?= $Theader ?>"  class="TSM_Theader TSM_Rheader"><?= I18N::translate('Records') . ' - ' . I18N::translate($Theader) . ' (' . view('components/TSMbadge', ['count' => $count, 'total' => $count]) . ')'; ?></th>
                    <th class="dontShow">...</th>
                    <th class="TSM_Theader"><?= I18N::translate('Action'); ?></th>
                </tr>
            </thead>
            <tbody name="<?= $Theader ?>">
                <?php foreach ($records as $record) : ?>
                    <tr xref="<?= $record->xref() ?>" class="TSM_Rline" >
                        <td>
                            <?= view('icons/record', ['record' => $record]); ?>
                            <a href="<?= e($record->url()); ?>">
                                <?= $record->fullName(); ?>
                            </a>
                        </td>
                        <td class="TSM_xref" >
                            <?php $xref= (string) $record->xref();
                                    $cLabel = $tagsXREFs[$xref];
                                    if (!$cLabel == []) :
                                        $xrefLabels = explode(";",$cLabel);
                                        foreach ($xrefLabels as $xLabel) : ?>
                                            <?= view('components/TSMbadgedText', ['text' => $xLabel]); ?>
                                  <?php endforeach; 
                                    endif; ?>
                        </td>
                        <td>
                            <a href="#" rel="nofollow" data-url="<?= $routeSDbAjax ?>" action="RemoveXREF" tree="<?= $tree->name() ?>" xref ="<?= $record->xref() ?>">
                                <button type="submit" class="btn btn-link" title="<?= I18N::translate('Remove record from overview'); ?>">
                                    <?= view('icons/delete'); ?>
                                </button>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="lineHalfHeight">&nbsp;</div>
    <?php endif; ?>
<?php endforeach; ?>
