<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Tree;

use HuHwt\WebtreesMods\TaggingServiceManager\Http\RequestHandlers\TSMchooseATag;

/**
 * @var string              $module
 * @var string              $activeTag
 * @var array<>             $TAGoptions
 * @var string              $routeSDbAjax
 * @var string              $routeATcAjax
 * @var string              $routeWReAjax
 * @var string              $dtitle
 * @var string              $stitle
 * @var Tree                $tree
 */

    $header_activeTag   = I18N::translate('Active Tag');

    $Ttitle = I18N::translate("Click here to choose the 'Active Tag'");

    $wt_s_id = Registry::idFactory()->id();

?>

<div class="TSMtah">
    <div name="TSMfloatHidden">
        <a href="#" rel="nofollow" data-url="<?= $routeSDbAjax ?>" action="TagsSave" tree="<?= $tree->name() ?>">
            <button id="TSMbtnSave" class="btn btn-secondary tsm-btn" title="<?= I18N::translate('Save tagging state to the database'); ?>" disabled>
                <?= view('icons/database'); ?><span><?= I18N::translate('save'); ?></span>
            </button>
        </a>
    </div>
    <div name="TSMfloatHidden">
        <div>
            <button id="TSMbtnPushAll" class="TSMshow_box btn btn-secondary tsm-btn-sm-2" title="<?= I18N::translate('Action: push Active Tag to all records in overview') ?>"  disabled>
                <?= view('icons/push-to-all'); ?><span><?= I18N::translate('Push to all'); ?></span>
            </button>
        </div>
    </div>
    <div name="TSMfloatHidden">
        <div>
            <button id="TSMbtnRemoveAll" class="TSMshow_box btn btn-secondary tsm-btn-sm-2" title="<?= I18N::translate('Action: remove Active Tag from all records in overview') ?>"  disabled>
                <?= view('icons/remove-all'); ?><span><?= I18N::translate('Remove from all'); ?></span>
            </button>
        </div>
    </div>
    <div name="TSMfloatHidden">
        <button id="TSMbtnRedo" class="btn btn-secondary tsm-btn tsm-btn-sm" type="button" title="<?= I18N::translate('Redo'); ?>" >
            <?= view('icons/redo'); ?><span><?= I18N::translate('Redo'); ?></span>
        </button>
        <div class="offLimits">
            <button id="TSMbtnRedo_DO" class="btn btn-secondary tsm-btn tsm-btn-sm" type="button" title="<?= I18N::translate('Redo'); ?>"
                    data-url="<?= $routeWReAjax ?>">
                <?= view('icons/redo'); ?><span><?= I18N::translate('Redo'); ?></span>
            </button>
        </div>
    </div>
    <div id="TSMfloat_drag" dtitle="<?= $dtitle ?>" class="hiddenLine">
        <p>&nbsp;</p>
    </div>
    <div id="TSMactTag" class="reactive">
        <button id="TSMbtnATag" class="btn btn-secondary tsm-btn-txt" type="button" title="<?= $Ttitle ?>" >
            <span><?= $header_activeTag ?></span>
        </button>
        <h6 class="hiddenLine" title="<?= $Ttitle ?>"><?= $header_activeTag ?></h6>
        <p><?= $activeTag ?></p>
        <div class="offLimits">
            <button id="TSMbtnATag_DO" class="btn btn-secondary tsm-btn-txt" type="submit" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
                data-wt-select-id="<?= $wt_s_id ?>" data-wt-href="<?= $routeATcAjax ?>" >
            </button>
        </div>
    </div>
</div>
